name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -out=plan.out

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

    env:
      TF_VAR_hostname: ${{ secrets.PANOS_HOSTNAME }}
      TF_VAR_username: ${{ secrets.PANOS_USERNAME }}
      TF_VAR_password: ${{ secrets.PANOS_PASSWORD }}
      # Add other required environment variables here
